# Generated by Django 4.0.2 on 2022-02-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0002_mbkkaround_mbkword_alter_mbkkaround_mbtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbkkaround',
            name='mbmethod',
            field=models.IntegerField(default=0),
        ),
    ]
