# Generated by Django 4.0.2 on 2022-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0003_mbkkaround_mbmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbkkaround',
            name='mbradius',
            field=models.IntegerField(default=0),
        ),
    ]
