# Generated by Django 4.0.2 on 2022-02-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0004_mbkkaround_mbradius'),
    ]

    operations = [
        migrations.CreateModel(
            name='mbkkdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtuserid', models.CharField(max_length=64)),
                ('dtlocid', models.IntegerField(default=99)),
                ('dtlocname', models.CharField(blank=True, max_length=256, null=True)),
                ('dtloclat', models.FloatField()),
                ('dtloclng', models.FloatField()),
                ('dtlocrating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dtlocaddress', models.CharField(blank=True, max_length=512, null=True)),
                ('dtlocphotourl', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
