# Generated by Django 4.0.2 on 2022-02-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0005_mbkkdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbkkdetail',
            name='dtlocaddress',
        ),
    ]
