# Generated by Django 4.0.2 on 2022-02-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0006_remove_mbkkdetail_dtlocaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbkkdetail',
            name='dtlocdistance',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
