typelist = [

{ 'typeid' : 1, 'en': 'accounting', 'cn': '会计' },
{ 'typeid' : 2, 'en': 'airport', 'cn': '机场' },
{ 'typeid' : 3, 'en': 'amusement_park', 'cn': '游乐场' },
{ 'typeid' : 4, 'en': 'aquarium', 'cn': '水族馆' },
{ 'typeid' : 5, 'en': 'art_gallery', 'cn': '艺术馆' },
{ 'typeid' : 6, 'en': 'atm', 'cn': 'ATM 机' },
{ 'typeid' : 7, 'en': 'bakery', 'cn': '面包店' },
{ 'typeid' : 8, 'en': 'bank', 'cn': '银行' },
{ 'typeid' : 9, 'en': 'bar', 'cn': '酒吧' },
{ 'typeid' : 10, 'en': 'beauty_salon', 'cn': '美容院' },
{ 'typeid' : 11, 'en': 'bicycle_store', 'cn': '自行车店' },
{ 'typeid' : 12, 'en': 'book_store', 'cn': '书店' },
{ 'typeid' : 13, 'en': 'bowling_alley', 'cn': '保龄球馆' },
{ 'typeid' : 14, 'en': 'bus_station', 'cn': '巴士站' },
{ 'typeid' : 15, 'en': 'cafe', 'cn': '咖啡馆' },
{ 'typeid' : 16, 'en': 'campground', 'cn': '营地' },
{ 'typeid' : 17, 'en': 'car_dealer', 'cn': '汽车经销商' },
{ 'typeid' : 18, 'en': 'car_rental', 'cn': '汽车租赁' },
{ 'typeid' : 19, 'en': 'car_repair', 'cn': '汽车维修' },
{ 'typeid' : 20, 'en': 'car_wash', 'cn': '洗车' },
{ 'typeid' : 21, 'en': 'casino', 'cn': '赌场' },
{ 'typeid' : 22, 'en': 'church', 'cn': '教堂' },
{ 'typeid' : 23, 'en': 'city_hall', 'cn': '市政厅' },
{ 'typeid' : 24, 'en': 'clothing_store', 'cn': '服装店' },
{ 'typeid' : 25, 'en': 'convenience_store', 'cn': '便利店' },
{ 'typeid' : 26, 'en': 'courthouse', 'cn': '法院' },
{ 'typeid' : 27, 'en': 'dentist', 'cn': '牙医' },
{ 'typeid' : 28, 'en': 'department_store', 'cn': '百货商店' },
{ 'typeid' : 29, 'en': 'doctor', 'cn': '医生' },
{ 'typeid' : 30, 'en': 'drugstore', 'cn': '药店' },
{ 'typeid' : 31, 'en': 'electrician', 'cn': '电工' },
{ 'typeid' : 32, 'en': 'electronics_store', 'cn': '电子商店' },
{ 'typeid' : 33, 'en': 'embassy', 'cn': '大使馆' },
{ 'typeid' : 34, 'en': 'fire_station', 'cn': '消防站' },
{ 'typeid' : 35, 'en': 'florist', 'cn': '花店' },
{ 'typeid' : 36, 'en': 'furniture_store', 'cn': '家具店' },
{ 'typeid' : 37, 'en': 'gas_station', 'cn': '加油站' },
{ 'typeid' : 38, 'en': 'gym', 'cn': '健身房' },
{ 'typeid' : 39, 'en': 'hair_care', 'cn': '护发' },
{ 'typeid' : 40, 'en': 'hardware_store', 'cn': '五金店' },
{ 'typeid' : 41, 'en': 'hindu_temple', 'cn': '印度教寺庙' },
{ 'typeid' : 42, 'en': 'home_goods_store', 'cn': '家品店' },
{ 'typeid' : 43, 'en': 'hospital', 'cn': '医院' },
{ 'typeid' : 44, 'en': 'insurance_agency', 'cn': '保险机构' },
{ 'typeid' : 45, 'en': 'jewelry_store', 'cn': '珠宝店' },
{ 'typeid' : 46, 'en': 'laundry', 'cn': '洗衣店' },
{ 'typeid' : 47, 'en': 'lawyer', 'cn': '律师' },
{ 'typeid' : 48, 'en': 'library', 'cn': '图书馆' },
{ 'typeid' : 49, 'en': 'light_rail_station', 'cn': '轻轨站' },
{ 'typeid' : 50, 'en': 'liquor_store', 'cn': '酒类商店' },
{ 'typeid' : 51, 'en': 'local_government_office', 'cn': '地方政府' },
{ 'typeid' : 52, 'en': 'locksmith', 'cn': '锁匠' },
{ 'typeid' : 53, 'en': 'lodging', 'cn': '住宿' },
{ 'typeid' : 54, 'en': 'meal_delivery', 'cn': '送餐服务' },
{ 'typeid' : 55, 'en': 'meal_takeaway', 'cn': '外卖' },
{ 'typeid' : 56, 'en': 'mosque', 'cn': '清真寺' },
{ 'typeid' : 57, 'en': 'movie_rental', 'cn': '租用电影' },
{ 'typeid' : 58, 'en': 'movie_theater', 'cn': '电影院' },
{ 'typeid' : 59, 'en': 'moving_company', 'cn': '搬家公司' },
{ 'typeid' : 60, 'en': 'museum', 'cn': '博物馆' },
{ 'typeid' : 61, 'en': 'night_club', 'cn': '夜总会' },
{ 'typeid' : 62, 'en': 'painter', 'cn': '油漆粉刷' },
{ 'typeid' : 63, 'en': 'park', 'cn': '公园' },
{ 'typeid' : 64, 'en': 'parking', 'cn': '停车场' },
{ 'typeid' : 65, 'en': 'pet_store', 'cn': '宠物店' },
{ 'typeid' : 66, 'en': 'pharmacy', 'cn': '药房' },
{ 'typeid' : 67, 'en': 'physiotherapist', 'cn': '物理治疗师' },
{ 'typeid' : 68, 'en': 'plumber', 'cn': '水管工' },
{ 'typeid' : 69, 'en': 'police', 'cn': '警察' },
{ 'typeid' : 70, 'en': 'post_office', 'cn': '邮局' },
{ 'typeid' : 71, 'en': 'primary_school', 'cn': '小学' },
{ 'typeid' : 72, 'en': 'real_estate_agency', 'cn': '房地产中介' },
{ 'typeid' : 73, 'en': 'restaurant', 'cn': '餐馆' },
{ 'typeid' : 74, 'en': 'roofing_contractor', 'cn': '屋顶工程' },
{ 'typeid' : 75, 'en': 'rv_park', 'cn': '房车停车场' },
{ 'typeid' : 76, 'en': 'school', 'cn': '学校' },
{ 'typeid' : 77, 'en': 'secondary_school', 'cn': '中学' },
{ 'typeid' : 78, 'en': 'shoe_store', 'cn': '鞋店' },
{ 'typeid' : 79, 'en': 'shopping_mall', 'cn': '购物中心' },
{ 'typeid' : 80, 'en': 'spa', 'cn': '水疗中心' },
{ 'typeid' : 81, 'en': 'stadium', 'cn': '体育馆' },
{ 'typeid' : 82, 'en': 'storage', 'cn': '仓库' },
{ 'typeid' : 83, 'en': 'store', 'cn': '商店' },
{ 'typeid' : 84, 'en': 'subway_station', 'cn': '地铁站' },
{ 'typeid' : 85, 'en': 'supermarket', 'cn': '超级市场' },
{ 'typeid' : 86, 'en': 'synagogue', 'cn': '犹太教堂' },
{ 'typeid' : 87, 'en': 'taxi_stand', 'cn': '出租车站' },
{ 'typeid' : 88, 'en': 'tourist_attraction', 'cn': '旅游景点' },
{ 'typeid' : 89, 'en': 'train_station', 'cn': '火车站' },
{ 'typeid' : 90, 'en': 'transit_station', 'cn': '中转站' },
{ 'typeid' : 91, 'en': 'travel_agency', 'cn': '旅行社' },
{ 'typeid' : 92, 'en': 'university', 'cn': '大学' },
{ 'typeid' : 93, 'en': 'veterinary_care', 'cn': '兽医护理' },
{ 'typeid' : 94, 'en': 'zoo', 'cn': '动物园' },


]

# typelist = [
# # 90
# { 'typeid' : 1, 'en': 'accounting', 'cn': '会计' },
# { 'typeid' : 2, 'en': 'airport', 'cn': '机场' },
# { 'typeid' : 3, 'en': 'aquarium', 'cn': '水族馆' },
# { 'typeid' : 4, 'en': 'art_gallery', 'cn': '艺术馆' },
# { 'typeid' : 5, 'en': 'atm', 'cn': 'ATM 机' },
# { 'typeid' : 6, 'en': 'bakery', 'cn': '面包店' },
# { 'typeid' : 7, 'en': 'bank', 'cn': '银行' },
# { 'typeid' : 8, 'en': 'bar', 'cn': '酒吧' },
# { 'typeid' : 9, 'en': 'beauty_salon', 'cn': '美容院' },
# { 'typeid' : 10, 'en': 'bicycle_store', 'cn': '自行车店' },
# { 'typeid' : 11, 'en': 'book_store', 'cn': '书店' },
# { 'typeid' : 12, 'en': 'bowling_alley', 'cn': '保龄球馆' },
# { 'typeid' : 13, 'en': 'bus_station', 'cn': '巴士站' },
# { 'typeid' : 14, 'en': 'cafe', 'cn': '咖啡馆' },
# { 'typeid' : 15, 'en': 'campground', 'cn': '营地' },
# { 'typeid' : 16, 'en': 'car_dealer', 'cn': '汽车经销商' },
# { 'typeid' : 17, 'en': 'car_rental', 'cn': '汽车租赁' },
# { 'typeid' : 18, 'en': 'car_repair', 'cn': '汽车维修' },
# { 'typeid' : 19, 'en': 'car_wash', 'cn': '洗车' },
# { 'typeid' : 20, 'en': 'casino', 'cn': '赌场' },
# { 'typeid' : 21, 'en': 'church', 'cn': '教堂' },
# { 'typeid' : 22, 'en': 'clothing_store', 'cn': '服装店' },
# { 'typeid' : 23, 'en': 'convenience_store', 'cn': '便利店' },
# { 'typeid' : 24, 'en': 'courthouse', 'cn': '法院' },
# { 'typeid' : 25, 'en': 'dentist', 'cn': '牙医' },
# { 'typeid' : 26, 'en': 'department_store', 'cn': '百货商店' },
# { 'typeid' : 27, 'en': 'doctor', 'cn': '医生' },
# { 'typeid' : 28, 'en': 'drugstore', 'cn': '药店' },
# { 'typeid' : 29, 'en': 'electrician', 'cn': '电工' },
# { 'typeid' : 30, 'en': 'electronics_store', 'cn': '电子商店' },
# { 'typeid' : 31, 'en': 'embassy', 'cn': '大使馆' },
# { 'typeid' : 32, 'en': 'fire_station', 'cn': '消防站' },
# { 'typeid' : 33, 'en': 'florist', 'cn': '花店' },
# { 'typeid' : 34, 'en': 'furniture_store', 'cn': '家具店' },
# { 'typeid' : 35, 'en': 'gas_station', 'cn': '加油站' },
# { 'typeid' : 36, 'en': 'gym', 'cn': '健身房' },
# { 'typeid' : 37, 'en': 'hair_care', 'cn': '护发' },
# { 'typeid' : 38, 'en': 'hardware_store', 'cn': '五金店' },
# { 'typeid' : 39, 'en': 'home_goods_store', 'cn': '家品店' },
# { 'typeid' : 40, 'en': 'hospital', 'cn': '医院' },
# { 'typeid' : 41, 'en': 'insurance_agency', 'cn': '保险机构' },
# { 'typeid' : 42, 'en': 'jewelry_store', 'cn': '珠宝店' },
# { 'typeid' : 43, 'en': 'laundry', 'cn': '洗衣店' },
# { 'typeid' : 44, 'en': 'lawyer', 'cn': '律师' },
# { 'typeid' : 45, 'en': 'library', 'cn': '图书馆' },
# { 'typeid' : 46, 'en': 'light_rail_station', 'cn': '轻轨站' },
# { 'typeid' : 47, 'en': 'liquor_store', 'cn': '酒类商店' },
# { 'typeid' : 48, 'en': 'local_government_office', 'cn': '地方政府' },
# { 'typeid' : 49, 'en': 'locksmith', 'cn': '锁匠' },
# { 'typeid' : 50, 'en': 'lodging', 'cn': '住宿' },
# { 'typeid' : 51, 'en': 'meal_delivery', 'cn': '送餐服务' },
# { 'typeid' : 52, 'en': 'meal_takeaway', 'cn': '外卖' },
# { 'typeid' : 53, 'en': 'mosque', 'cn': '清真寺' },
# { 'typeid' : 54, 'en': 'movie_rental', 'cn': '租用电影' },
# { 'typeid' : 55, 'en': 'movie_theater', 'cn': '电影院' },
# { 'typeid' : 56, 'en': 'moving_company', 'cn': '搬家公司' },
# { 'typeid' : 57, 'en': 'museum', 'cn': '博物馆' },
# { 'typeid' : 58, 'en': 'night_club', 'cn': '夜总会' },
# { 'typeid' : 59, 'en': 'painter', 'cn': '油漆粉刷' },
# { 'typeid' : 60, 'en': 'park', 'cn': '公园' },
# { 'typeid' : 61, 'en': 'parking', 'cn': '停车场' },
# { 'typeid' : 62, 'en': 'pet_store', 'cn': '宠物店' },
# { 'typeid' : 63, 'en': 'pharmacy', 'cn': '药房' },
# { 'typeid' : 64, 'en': 'physiotherapist', 'cn': '物理治疗师' },
# { 'typeid' : 65, 'en': 'plumber', 'cn': '水管工' },
# { 'typeid' : 66, 'en': 'police', 'cn': '警察' },
# { 'typeid' : 67, 'en': 'post_office', 'cn': '邮局' },
# { 'typeid' : 68, 'en': 'primary_school', 'cn': '小学' },
# { 'typeid' : 69, 'en': 'real_estate_agency', 'cn': '房地产中介' },
# { 'typeid' : 70, 'en': 'restaurant', 'cn': '餐馆' },
# { 'typeid' : 71, 'en': 'roofing_contractor', 'cn': '屋顶工程' },
# { 'typeid' : 72, 'en': 'school', 'cn': '学校' },
# { 'typeid' : 73, 'en': 'secondary_school', 'cn': '中学' },
# { 'typeid' : 74, 'en': 'shoe_store', 'cn': '鞋店' },
# { 'typeid' : 75, 'en': 'shopping_mall', 'cn': '购物中心' },
# { 'typeid' : 76, 'en': 'spa', 'cn': '水疗中心' },
# { 'typeid' : 77, 'en': 'stadium', 'cn': '体育馆' },
# { 'typeid' : 78, 'en': 'storage', 'cn': '仓库' },
# { 'typeid' : 79, 'en': 'store', 'cn': '商店' },
# { 'typeid' : 80, 'en': 'subway_station', 'cn': '地铁站' },
# { 'typeid' : 81, 'en': 'supermarket', 'cn': '超级市场' },
# { 'typeid' : 82, 'en': 'synagogue', 'cn': '犹太教堂' },
# { 'typeid' : 83, 'en': 'taxi_stand', 'cn': '出租车站' },
# { 'typeid' : 84, 'en': 'tourist_attraction', 'cn': '旅游景点' },
# { 'typeid' : 85, 'en': 'train_station', 'cn': '火车站' },
# { 'typeid' : 86, 'en': 'transit_station', 'cn': '中转站' },
# { 'typeid' : 87, 'en': 'travel_agency', 'cn': '旅行社' },
# { 'typeid' : 88, 'en': 'university', 'cn': '大学' },
# { 'typeid' : 89, 'en': 'veterinary_care', 'cn': '兽医护理' },
# { 'typeid' : 90, 'en': 'zoo', 'cn': '动物园' },


# ]

# # typelist = [

# # { 'typeid' : 1, 'en': 'accounting', 'cn': '会计' },
# # { 'typeid' : 2, 'en': 'airport', 'cn': '机场' },
# # { 'typeid' : 3, 'en': 'aquarium', 'cn': '水族馆' },
# # { 'typeid' : 4, 'en': 'art_gallery', 'cn': '艺术馆' },
# # { 'typeid' : 5, 'en': 'atm', 'cn': 'ATM 机' },
# # { 'typeid' : 6, 'en': 'bakery', 'cn': '面包店' },
# # { 'typeid' : 7, 'en': 'bank', 'cn': '银行' },
# # { 'typeid' : 8, 'en': 'bar', 'cn': '酒吧' },
# # { 'typeid' : 9, 'en': 'beauty_salon', 'cn': '美容院' },
# # { 'typeid' : 10, 'en': 'bicycle_store', 'cn': '自行车店' },
# # { 'typeid' : 11, 'en': 'book_store', 'cn': '书店' },
# # { 'typeid' : 12, 'en': 'bowling_alley', 'cn': '保龄球馆' },
# # { 'typeid' : 13, 'en': 'bus_station', 'cn': '巴士站' },
# # { 'typeid' : 14, 'en': 'cafe', 'cn': '咖啡馆' },
# # { 'typeid' : 15, 'en': 'campground', 'cn': '营地' },
# # { 'typeid' : 16, 'en': 'car_dealer', 'cn': '汽车经销商' },
# # { 'typeid' : 17, 'en': 'car_rental', 'cn': '汽车租赁' },
# # { 'typeid' : 18, 'en': 'car_repair', 'cn': '汽车维修' },
# # { 'typeid' : 19, 'en': 'car_wash', 'cn': '洗车' },
# # { 'typeid' : 20, 'en': 'casino', 'cn': '赌场' },
# # { 'typeid' : 21, 'en': 'cemetery', 'cn': '墓园' },
# # { 'typeid' : 22, 'en': 'church', 'cn': '教堂' },
# # { 'typeid' : 23, 'en': 'clothing_store', 'cn': '服装店' },
# # { 'typeid' : 24, 'en': 'convenience_store', 'cn': '便利店' },
# # { 'typeid' : 25, 'en': 'courthouse', 'cn': '法院' },
# # { 'typeid' : 26, 'en': 'dentist', 'cn': '牙医' },
# # { 'typeid' : 27, 'en': 'department_store', 'cn': '百货商店' },
# # { 'typeid' : 28, 'en': 'doctor', 'cn': '医生' },
# # { 'typeid' : 29, 'en': 'drugstore', 'cn': '药店' },
# # { 'typeid' : 30, 'en': 'electrician', 'cn': '电工' },
# # { 'typeid' : 31, 'en': 'electronics_store', 'cn': '电子商店' },
# # { 'typeid' : 32, 'en': 'embassy', 'cn': '大使馆' },
# # { 'typeid' : 33, 'en': 'fire_station', 'cn': '消防站' },
# # { 'typeid' : 34, 'en': 'florist', 'cn': '花店' },
# # { 'typeid' : 35, 'en': 'funeral_home', 'cn': '殡仪馆' },
# # { 'typeid' : 36, 'en': 'furniture_store', 'cn': '家具店' },
# # { 'typeid' : 37, 'en': 'gas_station', 'cn': '加油站' },
# # { 'typeid' : 38, 'en': 'gym', 'cn': '健身房' },
# # { 'typeid' : 39, 'en': 'hair_care', 'cn': '护发' },
# # { 'typeid' : 40, 'en': 'hardware_store', 'cn': '五金店' },
# # { 'typeid' : 41, 'en': 'home_goods_store', 'cn': '家品店' },
# # { 'typeid' : 42, 'en': 'hospital', 'cn': '医院' },
# # { 'typeid' : 43, 'en': 'insurance_agency', 'cn': '保险机构' },
# # { 'typeid' : 44, 'en': 'jewelry_store', 'cn': '珠宝店' },
# # { 'typeid' : 45, 'en': 'laundry', 'cn': '洗衣店' },
# # { 'typeid' : 46, 'en': 'lawyer', 'cn': '律师' },
# # { 'typeid' : 47, 'en': 'library', 'cn': '图书馆' },
# # { 'typeid' : 48, 'en': 'light_rail_station', 'cn': '轻轨站' },
# # { 'typeid' : 49, 'en': 'liquor_store', 'cn': '酒类商店' },
# # { 'typeid' : 50, 'en': 'local_government_office', 'cn': '地方政府办公室' },
# # { 'typeid' : 51, 'en': 'locksmith', 'cn': '锁匠' },
# # { 'typeid' : 52, 'en': 'lodging', 'cn': '住宿' },
# # { 'typeid' : 53, 'en': 'meal_delivery', 'cn': '送餐服务' },
# # { 'typeid' : 54, 'en': 'meal_takeaway', 'cn': '外卖' },
# # { 'typeid' : 55, 'en': 'mosque', 'cn': '清真寺' },
# # { 'typeid' : 56, 'en': 'movie_rental', 'cn': '租用电影' },
# # { 'typeid' : 57, 'en': 'movie_theater', 'cn': '电影院' },
# # { 'typeid' : 58, 'en': 'moving_company', 'cn': '搬家公司' },
# # { 'typeid' : 59, 'en': 'museum', 'cn': '博物馆' },
# # { 'typeid' : 60, 'en': 'night_club', 'cn': '夜总会' },
# # { 'typeid' : 61, 'en': 'painter', 'cn': '油漆粉刷' },
# # { 'typeid' : 62, 'en': 'park', 'cn': '公园' },
# # { 'typeid' : 63, 'en': 'parking', 'cn': '停车场' },
# # { 'typeid' : 64, 'en': 'pet_store', 'cn': '宠物店' },
# # { 'typeid' : 65, 'en': 'pharmacy', 'cn': '药房' },
# # { 'typeid' : 66, 'en': 'physiotherapist', 'cn': '物理治疗师' },
# # { 'typeid' : 67, 'en': 'plumber', 'cn': '水管工' },
# # { 'typeid' : 68, 'en': 'police', 'cn': '警察' },
# # { 'typeid' : 69, 'en': 'post_office', 'cn': '邮局' },
# # { 'typeid' : 70, 'en': 'primary_school', 'cn': '小学' },
# # { 'typeid' : 71, 'en': 'real_estate_agency', 'cn': '房地产中介机构' },
# # { 'typeid' : 72, 'en': 'restaurant', 'cn': '餐馆' },
# # { 'typeid' : 73, 'en': 'roofing_contractor', 'cn': '屋顶工程承包商' },
# # { 'typeid' : 74, 'en': 'school', 'cn': '学校' },
# # { 'typeid' : 75, 'en': 'secondary_school', 'cn': '中学' },
# # { 'typeid' : 76, 'en': 'shoe_store', 'cn': '鞋店' },
# # { 'typeid' : 77, 'en': 'shopping_mall', 'cn': '购物中心' },
# # { 'typeid' : 78, 'en': 'spa', 'cn': '水疗中心' },
# # { 'typeid' : 79, 'en': 'stadium', 'cn': '体育馆' },
# # { 'typeid' : 80, 'en': 'storage', 'cn': '仓库' },
# # { 'typeid' : 81, 'en': 'store', 'cn': '商店' },
# # { 'typeid' : 82, 'en': 'subway_station', 'cn': '地铁站' },
# # { 'typeid' : 83, 'en': 'supermarket', 'cn': '超级市场' },
# # { 'typeid' : 84, 'en': 'synagogue', 'cn': '犹太教堂' },
# # { 'typeid' : 85, 'en': 'taxi_stand', 'cn': '出租车站' },
# # { 'typeid' : 86, 'en': 'tourist_attraction', 'cn': '旅游景点' },
# # { 'typeid' : 87, 'en': 'train_station', 'cn': '火车站' },
# # { 'typeid' : 88, 'en': 'transit_station', 'cn': '中转站' },
# # { 'typeid' : 89, 'en': 'travel_agency', 'cn': '旅行社' },
# # { 'typeid' : 90, 'en': 'university', 'cn': '大学' },
# # { 'typeid' : 91, 'en': 'veterinary_care', 'cn': '兽医护理' },
# # { 'typeid' : 92, 'en': 'zoo', 'cn': '动物园' },

# # ]


# # # typelist = [
# # # { 'typeid' : 1, 'en': 'accounting', 'cn': '会计' },,
# # # { 'typeid' : 2, 'en': 'airport', 'cn': '机场' },,
# # # { 'typeid' : 3, 'en': 'amusement_park', 'cn': '游乐场' },,
# # # { 'typeid' : 4, 'en': 'aquarium', 'cn': '水族馆' },,
# # # { 'typeid' : 5, 'en': 'art_gallery', 'cn': '艺术馆' },,
# # # { 'typeid' : 6, 'en': 'atm', 'cn': 'ATM 机' },,
# # # { 'typeid' : 7, 'en': 'bakery', 'cn': '面包店' },,
# # # { 'typeid' : 8, 'en': 'bank', 'cn': '银行' },,
# # # { 'typeid' : 9, 'en': 'bar', 'cn': '酒吧' },,
# # # { 'typeid' : 10, 'en': 'beauty_salon', 'cn': '美容院' },,
# # # { 'typeid' : 11, 'en': 'bicycle_store', 'cn': '自行车店' },,
# # # { 'typeid' : 12, 'en': 'book_store', 'cn': '书店' },,
# # # { 'typeid' : 13, 'en': 'bowling_alley', 'cn': '保龄球馆' },,
# # # { 'typeid' : 14, 'en': 'bus_station', 'cn': '巴士站' },,
# # # { 'typeid' : 15, 'en': 'cafe', 'cn': '咖啡馆' },,
# # # { 'typeid' : 16, 'en': 'campground', 'cn': '营地' },,
# # # { 'typeid' : 17, 'en': 'car_dealer', 'cn': '汽车经销商' },,
# # # { 'typeid' : 18, 'en': 'car_rental', 'cn': '汽车租赁' },,
# # # { 'typeid' : 19, 'en': 'car_repair', 'cn': '汽车维修' },,
# # # { 'typeid' : 20, 'en': 'car_wash', 'cn': '洗车' },,
# # # { 'typeid' : 21, 'en': 'casino', 'cn': '赌场' },,
# # # { 'typeid' : 22, 'en': 'cemetery', 'cn': '墓园' },,
# # # { 'typeid' : 23, 'en': 'church', 'cn': '教堂' },,
# # # { 'typeid' : 24, 'en': 'city_hall', 'cn': '市政厅' },,
# # # { 'typeid' : 25, 'en': 'clothing_store', 'cn': '服装店' },,
# # # { 'typeid' : 26, 'en': 'convenience_store', 'cn': '便利店' },,
# # # { 'typeid' : 27, 'en': 'courthouse', 'cn': '法院' },,
# # # { 'typeid' : 28, 'en': 'dentist', 'cn': '牙医' },,
# # # { 'typeid' : 29, 'en': 'department_store', 'cn': '百货商店' },,
# # # { 'typeid' : 30, 'en': 'doctor', 'cn': '医生' },,
# # # { 'typeid' : 31, 'en': 'drugstore', 'cn': '药店' },,
# # # { 'typeid' : 32, 'en': 'electrician', 'cn': '电工' },,
# # # { 'typeid' : 33, 'en': 'electronics_store', 'cn': '电子商店' },,
# # # { 'typeid' : 34, 'en': 'embassy', 'cn': '大使馆' },,
# # # { 'typeid' : 35, 'en': 'fire_station', 'cn': '消防站' },,
# # # { 'typeid' : 36, 'en': 'florist', 'cn': '花店' },,
# # # { 'typeid' : 37, 'en': 'funeral_home', 'cn': '殡仪馆' },,
# # # { 'typeid' : 38, 'en': 'furniture_store', 'cn': '家具店' },,
# # # { 'typeid' : 39, 'en': 'gas_station', 'cn': '加油站' },,
# # # { 'typeid' : 40, 'en': 'gym', 'cn': '健身房' },,
# # # { 'typeid' : 41, 'en': 'hair_care', 'cn': '护发' },,
# # # { 'typeid' : 42, 'en': 'hardware_store', 'cn': '五金店' },,
# # # { 'typeid' : 43, 'en': 'hindu_temple', 'cn': '印度教寺庙' },,
# # # { 'typeid' : 44, 'en': 'home_goods_store', 'cn': '家品店' },,
# # # { 'typeid' : 45, 'en': 'hospital', 'cn': '医院' },,
# # # { 'typeid' : 46, 'en': 'insurance_agency', 'cn': '保险机构' },,
# # # { 'typeid' : 47, 'en': 'jewelry_store', 'cn': '珠宝店' },,
# # # { 'typeid' : 48, 'en': 'laundry', 'cn': '洗衣店' },,
# # # { 'typeid' : 49, 'en': 'lawyer', 'cn': '律师' },,
# # # { 'typeid' : 50, 'en': 'library', 'cn': '图书馆' },,
# # # { 'typeid' : 51, 'en': 'light_rail_station', 'cn': '轻轨站' },,
# # # { 'typeid' : 52, 'en': 'liquor_store', 'cn': '酒类商店' },,
# # # { 'typeid' : 53, 'en': 'local_government_office', 'cn': '地方政府办公室' },,
# # # { 'typeid' : 54, 'en': 'locksmith', 'cn': '锁匠' },,
# # # { 'typeid' : 55, 'en': 'lodging', 'cn': '住宿' },,
# # # { 'typeid' : 56, 'en': 'meal_delivery', 'cn': '送餐服务' },,
# # # { 'typeid' : 57, 'en': 'meal_takeaway', 'cn': '外卖' },,
# # # { 'typeid' : 58, 'en': 'mosque', 'cn': '清真寺' },,
# # # { 'typeid' : 59, 'en': 'movie_rental', 'cn': '租用电影' },,
# # # { 'typeid' : 60, 'en': 'movie_theater', 'cn': '电影院' },,
# # # { 'typeid' : 61, 'en': 'moving_company', 'cn': '搬家公司' },,
# # # { 'typeid' : 62, 'en': 'museum', 'cn': '博物馆' },,
# # # { 'typeid' : 63, 'en': 'night_club', 'cn': '夜总会' },,
# # # { 'typeid' : 64, 'en': 'painter', 'cn': '油漆工' },,
# # # { 'typeid' : 65, 'en': 'park', 'cn': '公园' },,
# # # { 'typeid' : 66, 'en': 'parking', 'cn': '停车场' },,
# # # { 'typeid' : 67, 'en': 'pet_store', 'cn': '宠物店' },,
# # # { 'typeid' : 68, 'en': 'pharmacy', 'cn': '药房' },,
# # # { 'typeid' : 69, 'en': 'physiotherapist', 'cn': '物理治疗师' },,
# # # { 'typeid' : 70, 'en': 'plumber', 'cn': '水管工' },,
# # # { 'typeid' : 71, 'en': 'police', 'cn': '警察' },,
# # # { 'typeid' : 72, 'en': 'post_office', 'cn': '邮局' },,
# # # { 'typeid' : 73, 'en': 'primary_school', 'cn': '小学' },,
# # # { 'typeid' : 74, 'en': 'real_estate_agency', 'cn': '房地产中介机构' },,
# # # { 'typeid' : 75, 'en': 'restaurant', 'cn': '餐馆' },,
# # # { 'typeid' : 76, 'en': 'roofing_contractor', 'cn': '屋顶工程承包商' },,
# # # { 'typeid' : 77, 'en': 'rv_park', 'cn': '房车停车场' },,
# # # { 'typeid' : 78, 'en': 'school', 'cn': '学校' },,
# # # { 'typeid' : 79, 'en': 'secondary_school', 'cn': '中学' },,
# # # { 'typeid' : 80, 'en': 'shoe_store', 'cn': '鞋店' },,
# # # { 'typeid' : 81, 'en': 'shopping_mall', 'cn': '购物中心' },,
# # # { 'typeid' : 82, 'en': 'spa', 'cn': '水疗中心' },,
# # # { 'typeid' : 83, 'en': 'stadium', 'cn': '体育馆' },,
# # # { 'typeid' : 84, 'en': 'storage', 'cn': '仓库' },,
# # # { 'typeid' : 85, 'en': 'store', 'cn': '商店' },,
# # # { 'typeid' : 86, 'en': 'subway_station', 'cn': '地铁站' },,
# # # { 'typeid' : 87, 'en': 'supermarket', 'cn': '超级市场' },,
# # # { 'typeid' : 88, 'en': 'synagogue', 'cn': '犹太教堂' },,
# # # { 'typeid' : 89, 'en': 'taxi_stand', 'cn': '出租车站' },,
# # # { 'typeid' : 90, 'en': 'tourist_attraction', 'cn': '旅游景点' },,
# # # { 'typeid' : 91, 'en': 'train_station', 'cn': '火车站' },,
# # # { 'typeid' : 92, 'en': 'transit_station', 'cn': '中转站' },,
# # # { 'typeid' : 93, 'en': 'travel_agency', 'cn': '旅行社' },,
# # # { 'typeid' : 94, 'en': 'university', 'cn': '大学' },,
# # # { 'typeid' : 95, 'en': 'veterinary_care', 'cn': '兽医护理' },,
# # # { 'typeid' : 96, 'en': 'zoo', 'cn': '动物园' },,
# # # ]